# ======================================================================
# Sinclair ZX Spectrum
# ======================================================================
	include ../../Makefile.inc

all: network.rom

clean:
	@$(RM) *.lst *.rom

network.rom: network.z80 block.z80 machinetype.z80 if1/*.z80 plus3/*.z80
