# ======================================================================
# Sinclair ZX Spectrum
# ======================================================================
	include ../../Makefile.inc

all: main.rom

clean:
	@$(RM) *.lst *.rom *.tzx

main.rom: main.z80 network.z80 ui.z80 menu.z80
