# ======================================================================
# Sinclair ZX Spectrum
# ======================================================================
	include ../../Makefile.inc

all: main.rom

clean:
	$(RM) *.lst *.rom *.tzx

main.rom: main.z80
