# ======================================================================
# Sinclair ZX Spectrum
# ======================================================================
	include ../../Makefile.inc

all: main.rom

clean:
	@$(RM) *.lst *.rom *.tzx

main.rom: *.z80 network/*.z80 network/*/*.z80
